server:
  port: 8030

spring:
  application:
    name: oauth2-gateway
  redis:
    host: 127.0.0.1
    database: 0

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    oauth2-server:
      path: /server/**
      serviceId: oauth2-server
    oauth2-client:
          path: /client/**
          serviceId: oauth2-client

logging.level:org.springframework: DEBUG

security:
  oauth2:
    resource:
      filter-order: 3

requestMatcher:
  content: /oauth2-server/server/order/**,/oauth2-client/client/order/**
